### ISSUE TITLE
Contributing to nixpkgs + license?

### ISSUE THREAD

**Issue by Icy-Thought** [VergeDX/config-nixpkgs#1]
Came across your repository while searching for a `flat-remix-gnome` nixpkg and it made me question what could've been the hindrance that allowed you to refrain from pushing forward several of your packaging attempts to NixOS/nixpkgs.

I do wish that this is not an impossible task for you, but if for whatever reason it is I would gladly like to ask for your permission to use this repository as a motivation for maintaining some of the provided packages in your package dir.

And also, please add a license to your repository!

**Comment by VergeDX** [comment]
I can make a PR for `NixOS/nixpkgs` if you are willing to, If you like to make yourself, welcome to copy any file from this repo.
I don't want to add a license because I always do `nixpkgs-fmt *` command, this command will reformat the LICENSE file, which is quite annoying XD

**Comment by Icy-Thought** [comment]
Was thinking whether you would be interested in submitting a PR of `flat-remix-gnome` and `sf-arabic` to NixOS/nixpkgs. Would appreciate it if you could, 谢谢！ :smile:

**Comment by VergeDX** [comment]
According to the answer of [Apple Community thread #7493969](https://discussions.apple.com/thread/7493969), copying and distributing the electronic font files made available in Font Book is prohibited.
If I have free time, I will make a PR for `flat-remix-gnome`.

**Comment by Icy-Thought** [comment]
Unfortunate to hear that..

Found a well-designed arabic font `Noto Kufi Arabic` in nixpkgs after browsing through nixpkgs looking for a possible candidates to replace the Apple font. I suggest you have a look at it if you want something that is currently available in nixpkgs. ;)

**Comment by VergeDX** [comment]
`flat-remix-gnome` -> master: https://github.com/NixOS/nixpkgs/pull/128278
